version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news_api
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - ollama
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: news_worker
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
      - ollama
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: news_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: news_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: news
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    # Optional: pull model on start
    command: serve

volumes:
  postgres_data:
  ollama: