version: "3.9"

services:
  api:
    build: .
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  worker:
    build: .
    command: celery -A app.workers.celery_app worker --loglevel=info --pool=solo
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434

  beat:
    build: .
    command: celery -A app.workers.celery_app beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - worker

  redis:
    image: redis:7
    container_name: news-redis
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: news-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: news
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11435:11434"        # ← Changed to 11435 on host
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data: