services:

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: news_api

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - postgres
      - redis



  worker:

    build:
      context: .
      dockerfile: Dockerfile.worker

    container_name: news_worker

    env_file:
      - .env

    depends_on:
      - redis
      - postgres



  redis:

    image: redis:7

    container_name: news_redis

    ports:
      - "6379:6379"



  postgres:

    image: postgres:16

    container_name: news_postgres

    environment:

      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: news

    ports:

      - "5432:5432"

    volumes:

      - postgres_data:/var/lib/postgresql/data



  ollama:

    image: ollama/ollama

    container_name: ollama

    ports:

      - "11434:11434"

    volumes:

      - ollama:/root/.ollama



volumes:

  postgres_data:

  ollama: